"""Parquet lake writing utilities for fetched market data."""
# pyright: reportUnknownMemberType=false, reportUnknownVariableType=false, reportUnknownArgumentType=false

from __future__ import annotations

from ingestion import lake_bronze_writes as _lake_bronze_writes
from ingestion import lake_dataframe as _lake_dataframe
from ingestion import lake_queries as _lake_queries
from ingestion import lake_reads as _lake_reads
from ingestion import lake_records as _lake_records
from ingestion import lake_writes as _lake_writes
from ingestion.lake_layout import (
    partition_path,
)
from ingestion.lake_sidecars import (
    ensure_bronze_sidecars,
)

__all__ = ["ensure_bronze_sidecars", "partition_path"]

NaturalKey = _lake_writes.NaturalKey
latest_open_time_in_lake = _lake_queries.latest_open_time_in_lake
latest_open_time_in_lake_by_dataset = _lake_queries.latest_open_time_in_lake_by_dataset
open_time_bounds_in_lake_by_dataset = _lake_queries.open_time_bounds_in_lake_by_dataset
open_times_in_lake = _lake_queries.open_times_in_lake
open_times_in_lake_by_dataset = _lake_queries.open_times_in_lake_by_dataset
partition_dates_in_lake_by_dataset = _lake_queries.partition_dates_in_lake_by_dataset
load_combined_dataframe_from_lake = _lake_dataframe.load_combined_dataframe_from_lake
load_funding_from_lake = _lake_reads.load_funding_from_lake
load_open_interest_from_lake = _lake_reads.load_open_interest_from_lake
load_spot_candles_from_lake = _lake_reads.load_spot_candles_from_lake
record_natural_key = _lake_writes.record_natural_key
merge_and_deduplicate_rows = _lake_writes.merge_and_deduplicate_rows
_require_pyarrow = _lake_writes.require_pyarrow
_write_partition_file = _lake_writes.write_partition_file
_write_grouped_rows = _lake_writes.write_grouped_rows
utc_run_id = _lake_records.utc_run_id
candle_partition_key = _lake_records.candle_partition_key
candle_record = _lake_records.candle_record
open_interest_partition_key = _lake_records.open_interest_partition_key
open_interest_record = _lake_records.open_interest_record
funding_partition_key = _lake_records.funding_partition_key
funding_record = _lake_records.funding_record
trade_partition_key = _lake_records.trade_partition_key
trade_record = _lake_records.trade_record
volatility_partition_key = _lake_records.volatility_partition_key
volatility_record = _lake_records.volatility_record
save_spot_candles_parquet_lake = _lake_bronze_writes.save_spot_candles_parquet_lake
save_open_interest_parquet_lake = _lake_bronze_writes.save_open_interest_parquet_lake
save_funding_parquet_lake = _lake_bronze_writes.save_funding_parquet_lake
save_volatility_parquet_lake = _lake_bronze_writes.save_volatility_parquet_lake
save_trades_parquet_lake = _lake_bronze_writes.save_trades_parquet_lake
